packages:
  - packages/@befide/bf2035-inventory
  - packages/@befide/bf2035-meta
  - packages/@befide/bf2035-report

catalog:
  "@astrojs/check": 0.9.4
  "@astrojs/mdx": 4.3.5
  "@astrojs/sitemap": 3.6.0
  "@astrojs/starlight-tailwind": 4.0.1
  "@astrojs/starlight": 0.36.0
  "@astrojs/ts-plugin": 1.10.4
  "@eslint/js": 9.36.0
  "@eslint/markdown": 7.2.0
  "@fontsource/barlow-condensed": 5.2.8
  "@fontsource/barlow-semi-condensed": 5.2.7
  "@nanostores/persistent": 1.1.0
  "@pagefind/default-ui": 1.4.0
  "@tailwindcss/vite": 4.1.13
  "@types/crossfilter": 0.0.38
  "@types/d3": 7.4.3
  "puppeteer-core": 24.22.0
  "astro-auto-import": 0.4.4
  "astro-pagefind": 1.8.5
  "stylus": 0.64.0

  "@types/dc": 4.2.5
  "@types/jsdom": 21.1.7
  "@types/remove-markdown": 0.3.4
  "@typescript-eslint/eslint-plugin": 8.44.0
  "@typescript-eslint/parser": 8.44.0
  "@typescript-eslint/types": 8.44.0
  "@vite-pwa/assets-generator": 1.0.1
  "@vite-pwa/astro": 1.1.0
  "@zokki/astro-purgecss": 1.0.4
  astro-breadcrumbs: 3.3.1
  astro-capo: 0.0.1
  astro-d2: 0.8.0
  astro-eslint-parser: 1.2.2
  astro-icon: 1.1.5
  astro: 5.13.9
  autoprefixer: 10.4.21
  crossfilter2: 1.5.4
  cssnano: 7.1.1
  csv42: 5.0.3
  d2: 31.10.2
  d3: 7.9.0
  dc: 4.2.7
  dotenv: 17.2.2
  eslint-config-prettier: 10.1.8
  eslint-plugin-astro: 1.3.1
  eslint-plugin-import: 2.32.0
  eslint-plugin-jsx-a11y: 6.10.2
  eslint-plugin-n: 17.23.1
  eslint-plugin-prettier: 5.5.4
  eslint-plugin-promise: 7.2.1
  eslint: 9.36.0
  fast-cartesian: 9.0.1
  file-saver: 2.0.5
  globals: 16.4.0
  jsdom: 27.0.0
  nanostores: 1.0.1
  organize-imports-cli: 0.10.0
  pagedjs: 0.5.0-beta.2
  pagefind: 1.4.0
  playwright: 1.55.0
  postcss-import: 16.1.1
  "@trivago/prettier-plugin-sort-imports": 5.2.2
  postcss-preset-env: 10.4.0
  postcss: 8.5.6
  prettier-eslint: 16.4.2
  prettier-package-json: 2.8.0
  prettier-plugin-astro-organize-imports: 0.4.11
  prettier-plugin-astro: 0.14.1
  prettier-plugin-packagejson: 2.5.19
  prettier-plugin-tailwindcss: 0.6.14
  prettier: 3.6.2
  read-yaml-file: 2.1.0
  rehype-add-classes: 1.0.0
  rehype-citation: 2.3.1
  rehype-figure: 1.0.1
  rehype-rewrite: 4.0.2
  rehype-stringify: 10.0.1
  remark-directive: 4.0.0
  remark-gfm: 4.0.1
  remark-numbered-footnote-labels: 1.1.0
  remark-parse: 11.0.0
  remark-rehype: 11.1.2
  remark-sectionize: 2.1.0
  remove-markdown: 0.6.2
  sharp-ico: 0.1.5
  sharp: 0.34.4
  starlight-auto-sidebar: 0.1.2
  starlight-image-zoom: 0.13.0
  starlight-theme-obsidian: 0.4.1
  stylelint-config-prettier: 9.0.5
  stylelint-config-standard: 39.0.0
  stylelint-config-tailwindcss: 1.0.0
  stylelint-prettier: 5.0.3
  stylelint: 16.24.0
  tailwind: 4.0.0
  tailwindcss: 4.1.13
  topojson-client: 3.1.0
  tornis: 0.3.6
  ts-node: 10.9.2
  typescript-eslint-parser-for-extra-files: 0.9.0
  typescript-eslint: 8.44.0
  typescript: 5.9.2
  unified: 11.0.5
  unist-util-visit: 5.0.0
  unplugin-unused: 0.5.3
  vite-plugin-pwa: 1.0.3
  workbox-window: 7.3.0
  yaml: 2.8.1
  zotero-api-client: 0.47.0
