/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    ColumnGroup: typeof import('primevue/columngroup')['default']
    copy: typeof import('./src/components/domain/FormalOrganizations copy.vue')['default']
    Courses: typeof import('./src/components/domain/Courses.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DataView: typeof import('primevue/dataview')['default']
    Facilities: typeof import('./src/components/domain/Facilities.vue')['default']
    FormalOrganizations: typeof import('./src/components/domain/FormalOrganizations.vue')['default']
    Organizations: typeof import('./src/components/domain/Organizations.vue')['default']
    OrganizationsTree: typeof import('./src/components/domain/OrganizationsTree.vue')['default']
    OrganizationTree: typeof import('./src/components/domain/OrganizationTree.vue')['default']
    ProgramOIfStudies: typeof import('./src/components/domain/ProgramOIfStudies.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Row: typeof import('primevue/row')['default']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Tag: typeof import('primevue/tag')['default']
    Taxonomy: typeof import('./src/components/domain/Taxonomy.vue')['default']
    TaxonomyTree: typeof import('./src/components/domain/TaxonomyTree.vue')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    TreeTable: typeof import('primevue/treetable')['default']
    WorkingGroups: typeof import('./src/components/domain/WorkingGroups.vue')['default']
  }
}
